# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_data <- function(stringname, fillMiss = "none") {
    .Call('_HSS_read_data', PACKAGE = 'HSS', stringname, fillMiss)
}

scaleC <- function(X) {
    .Call('_HSS_scaleC', PACKAGE = 'HSS', X)
}

scaleC_ref <- function(X) {
    .Call('_HSS_scaleC_ref', PACKAGE = 'HSS', X)
}

